<a href="https://colab.research.google.com/github/greatjapanese/DeepLearningLate/blob/main/_0920.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#モジュールを使う
##import文でモジュールを読み込んで使う

In [ ]:
#mathモジュールを読み込む
import math
print(math.pi)


3.141592653589793


In [ ]:
import math
print(math.pi)
print(math.pow(5,2))
print(math.sort(9))


3.141592653589793
25.0


AttributeError: ignored

In [ ]:
import numpy as np


#numpy配列を作る

In [ ]:
a = np.array([5,7,3,1,4,3])
print(a)

[5 7 3 1 4 3]


##Numpyで配列の操作をしてみる
###配列を構成しなおす

In [ ]:
#現在、aは1行1次元配列
print(a)
#aを３行２列の２次元配列に構成しなおす
b = a.reshape([3,2])
print(b)

[5 7 3 1 4 3]
[[5 7]
 [3 1]
 [4 3]]


###numpy配列の中身を初期化して作る

In [ ]:
#3行4列の0が入った2次元配列を作る
c = np.zeros((3,4))
print(c)
#ランダムな値が入った配列を作る
np.random()

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


TypeError: ignored

In [ ]:
##Numpyのスライスのやり方
##スライスの指定の仕方[start:stop:step]で指定する

In [ ]:
#リストのスライス
l = list(range(10))#0～9までの10個の要素のリスト
print(l)
print(l[4:8])
print(l[::-1])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[4, 5, 6, 7]


In [ ]:
a = np.arange(10)
print(a)
print(a[2:8])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]


In [ ]:
print(a)
a[3:6] = 100
print(a
      )

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2 100 100 100   6   7   8   9]


In [ ]:
a[3:6] = [100,200,300]
print(a)

[  0   1   2 100 200 300   6   7   8   9]


In [ ]:
a = np.arange(10)
print(a)
a[2:8:2] = 100
print(a)

[0 1 2 3 4 5 6 7 8 9]
[  0   1 100   3 100   5 100   7   8   9]


#多次元配列のndarrayのスライス

In [ ]:
#3行4列の2次元配列を作る
a = np.arange(12).reshape(3,4)
print(a)
print(a[1:,1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 5  6]
 [ 9 10]]


##多次元へのスライス代入

In [ ]:
import numpy as np

###多次元のndarrayへのstepを使ったスライスでの代入


In [ ]:
a = np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(a[1:,::2])

[[ 4  6]
 [ 8 10]]


In [ ]:
print(a[:2:,::3])

[[0 3]
 [4 7]]


In [ ]:
a[1:,::2] = [100,200]
print(a)
a[1:,::2] = [[100,200],[300,400]]
print(a)



[[  0   1   2   3]
 [100   5 200   7]
 [100   9 200  11]]
[[  0   1   2   3]
 [100   5 200   7]
 [300   9 400  11]]
